export {
    publicInquirySubmitSchema,
    inquiryListQuerySchema,
    inquiryUpdateSchema,
    inquiryNoteCreateSchema,
    inquiryReplyCreateSchema,
    inquiryBulkIdsSchema,
    inquiryBulkStatusSchema,
    inquiryStatusSchema,
    type PublicInquirySubmitInput,
    type InquiryListQuery,
    type InquiryUpdateInput,
    type InquiryNoteCreateInput,
    type InquiryReplyCreateInput,
    type InquiryBulkIdsInput,
    type InquiryBulkStatusInput,
    type InquiryStatus,
} from '@trio/shared/inquiry';
